Repository BeatingCodingame/python3-code-vs-zombie, pull requests merged in 2020-11, with the labels that each got.

#1 added game objective
  README.md
Labels: documentation

#8 Better Code
  codeingame.py
  test_codeingame.py
Labels: enhancement

#14 Resolves #10 #3 #2
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  assets/banner.jpg
  assets/simulation_example.png
  codeingame.py
  poetry.lock
  pyproject.toml
  simulations/2_zombies.siml
  simulations/2_zombies_redux.siml
  simulations/3_vs_3.siml
  simulations/columns_of_death.siml
  simulations/combo_opportunity.siml
  simulations/cross.siml
  simulations/devastation.siml
  simulations/flanked.siml
  simulations/grave_danger.siml
  simulations/grid.siml
  simulations/hoard.siml
  simulations/rectangle.siml
  simulations/rescue_mission.siml
  simulations/rows_to_defend.siml
  simulations/rows_to_defend_redux.siml
  simulations/scared_human.siml
  simulations/simple.siml
  simulations/split_2th_reflex.siml
  simulations/swervy_pattern.siml
  simulations/triangle.siml
  simulations/unavoidable_death.siml
  simulator/__init__.py
  test_codeingame.py
Labels: enhancement

#20 PR to resolve #13 #19
  .github/workflow/ci.yml
  .gitignore
  codeingame.py
  pyproject.toml
Labels: bug
